name: Build Gatsby

on:
  push:
    branches:
      - develop

jobs:
  build_gatsby:
    runs-on: ubuntu-latest
    name: Build Gatsby
    steps: 

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: install dependencies
        run: yarn install

      - name: Build Gatsby
        run: yarn build

      - name: Deploy to Github Pages
        uses: maxheld83/ghpages@v0.2.1
        env: 
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}          
          BUILD_DIR: 'public/'
